# Site settings
title: Elizabeth Garber
description: Change Maker
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Elizabeth Garber
user_description: "I’m a Strategic Intrapreneur: I’ll maximise revenues, reduce costs, and achieve organisational goals by implementing holistic, evidence-based interventions. In reality, this is all about understanding people and systems to lead them through complex change – cultural, technological, and everything in between."
user_title: Strategist and Change-Maker
email: eliza.garber@gmail.com
twitter_username: lorem_ipsum
github_username: 
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
